// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package editor

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// ============================================================================
// File Action Buttons — use in Gitea detail.templ file list
// ============================================================================

// FileEditButtons renders Monaco/nvim edit buttons for a file row.
// Add to the file list in detail.templ:
//
//	@editor.FileEditButtons(repoID, file.Path, currentBranch)
func FileEditButtons(repoID, filePath, ref string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity\"><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/editor/monaco?repo=%s&file=%s&ref=%s", repoID, filePath, ref)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/editor/file_actions.templ`, Line: 16, Col: 102}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"px-2 py-0.5 text-xs rounded bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 transition-colors\" title=\"Edit in Monaco (quick edit)\"><i class=\"fas fa-edit mr-1\"></i>Edit</a> <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.SafeURL
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/editor/nvim?repo=%s&file=%s&ref=%s", repoID, filePath, ref)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/editor/file_actions.templ`, Line: 21, Col: 100}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"px-2 py-0.5 text-xs rounded bg-green-500/10 text-green-400 hover:bg-green-500/20 transition-colors\" title=\"Edit in Neovim (full editor)\"><i class=\"fas fa-terminal mr-1\"></i>nvim</a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// FileEditLink returns the Monaco editor URL for a file.
// Use for making file names clickable in the Gitea detail file browser:
//
//	<a href={ templ.SafeURL(editor.MonacoURL(repoID, file.Path, ref)) }>
//	  { file.Name }
//	</a>
func MonacoURL(repoID, filePath, ref string) string {
	return fmt.Sprintf("/editor/monaco?repo=%s&file=%s&ref=%s", repoID, filePath, ref)
}

func NvimURL(repoID, filePath, ref string) string {
	return fmt.Sprintf("/editor/nvim?repo=%s&file=%s&ref=%s", repoID, filePath, ref)
}

var _ = templruntime.GeneratedTemplate
